export const questions = [
  { id: "real", en: "Is your character a real person?", de: "Ist deine Figur eine echte Person?" },
  { id: "personallyKnown", en: "Do you know this person personally?", de: "Kennst du diese Person persönlich?" },
  { id: "family", en: "Is this person part of your family?", de: "Gehört diese Person zu deiner Familie?" },
  { id: "parent", en: "Is this person one of your parents?", de: "Ist diese Person ein Elternteil von dir?" },
  { id: "sibling", en: "Is this person your sibling?", de: "Ist diese Person dein Bruder oder deine Schwester?" },
  { id: "grandparent", en: "Is this person one of your grandparents?", de: "Ist diese Person ein Großelternteil von dir?" },
  { id: "yourChild", en: "Is this person your child?", de: "Ist diese Person dein Kind?" },
  { id: "romantic", en: "Do you have romantic feelings for this person?", de: "Hast du romantische Gefühle für diese Person?" },
  { id: "partner", en: "Are you in a relationship with this person?", de: "Bist du mit dieser Person zusammen?" },
  { id: "friend", en: "Is this person a friend of yours?", de: "Ist diese Person mit dir befreundet?" },
  { id: "schoolWork", en: "Do you mainly know this person from school or work?", de: "Kennst du diese Person hauptsächlich aus Schule oder Arbeit?" },
  { id: "alive", en: "Is your character alive today?", de: "Lebt deine Figur heute noch?" },
  { id: "female", en: "Is your character female?", de: "Ist deine Figur weiblich?" },
  { id: "musician", en: "Is your character famous for making music?", de: "Ist deine Figur für Musik bekannt?" },
  { id: "musicGroup", en: "Was your character once famous as part of a music group?", de: "Wurde deine Figur als Mitglied einer Musikgruppe berühmt?" },
  { id: "athlete", en: "Is your character a professional athlete?", de: "Ist deine Figur Profisportler oder Profisportlerin?" },
  { id: "politician", en: "Is your character connected to politics?", de: "Hat deine Figur mit Politik zu tun?" },
  { id: "scientist", en: "Is your character known for science or invention?", de: "Ist deine Figur für Wissenschaft oder Erfindungen bekannt?" },
  { id: "artist", en: "Is your character known for visual art?", de: "Ist deine Figur für bildende Kunst bekannt?" },
  { id: "entrepreneur", en: "Is your character a famous business founder?", de: "Ist deine Figur als Unternehmensgründer bekannt?" },
  { id: "internet", en: "Did your character become famous mainly through the internet?", de: "Wurde deine Figur hauptsächlich durch das Internet berühmt?" },
  { id: "royalty", en: "Is your character royal?", de: "Ist deine Figur königlich?" },
  { id: "historical", en: "Did your character live mainly before the 20th century?", de: "Lebte deine Figur hauptsächlich vor dem 20. Jahrhundert?" },
  { id: "fictional", en: "Does your character come from a fictional story?", de: "Stammt deine Figur aus einer erfundenen Geschichte?" },
  { id: "magic", en: "Can your character use magic?", de: "Kann deine Figur Magie benutzen?" },
  { id: "superhero", en: "Is your character a superhero?", de: "Ist deine Figur ein Superheld oder eine Superheldin?" },
  { id: "masked", en: "Does your character usually hide their face?", de: "Verdeckt deine Figur normalerweise ihr Gesicht?" },
  { id: "animated", en: "Is your character usually animated?", de: "Ist deine Figur normalerweise animiert?" },
  { id: "game", en: "Did your character originate in a video game?", de: "Stammt deine Figur ursprünglich aus einem Videospiel?" },
  { id: "space", en: "Is your character strongly connected to space?", de: "Hat deine Figur viel mit dem Weltraum zu tun?" },
  { id: "detective", en: "Is your character a detective?", de: "Ist deine Figur ein Detektiv oder eine Detektivin?" },
  { id: "villain", en: "Is your character best known as a villain?", de: "Ist deine Figur hauptsächlich als Bösewicht bekannt?" },
  { id: "powers", en: "Does your character have superhuman powers?", de: "Hat deine Figur übermenschliche Kräfte?" },
  { id: "electric", en: "Is your character associated with electricity?", de: "Wird deine Figur mit Elektrizität verbunden?" },
  { id: "young", en: "Is your character a child or teenager for most of their story?", de: "Ist deine Figur während des Großteils ihrer Geschichte ein Kind oder Teenager?" },
  { id: "nonhuman", en: "Is your character non-human?", de: "Ist deine Figur nicht menschlich?" },
  { id: "american", en: "Is your character mainly associated with the United States?", de: "Ist deine Figur hauptsächlich den USA zuzuordnen?" },
  { id: "european", en: "Is your character mainly associated with Europe?", de: "Ist deine Figur hauptsächlich Europa zuzuordnen?" },
  { id: "movie", en: "Is your character or person best known through movies?", de: "Ist deine Figur oder Person vor allem durch Filme bekannt?" },
  { id: "red", en: "Is the color red strongly associated with your character?", de: "Wird deine Figur stark mit der Farbe Rot verbunden?" },
  { id: "actor", en: "Is your character famous for acting?", de: "Ist deine Figur für Schauspiel bekannt?" },
  { id: "writer", en: "Is your character known for writing?", de: "Ist deine Figur für das Schreiben bekannt?" },
  { id: "tv", en: "Is your character or person best known through a TV series?", de: "Ist deine Figur oder Person vor allem durch eine Serie bekannt?" },
  { id: "anime", en: "Is your character from anime or manga?", de: "Stammt deine Figur aus Anime oder Manga?" },
  { id: "animal", en: "Is your character an animal?", de: "Ist deine Figur ein Tier?" },
  { id: "robot", en: "Is your character a robot or machine?", de: "Ist deine Figur ein Roboter oder eine Maschine?" },
  { id: "football", en: "Is your character famous for football?", de: "Ist deine Figur für Fußball berühmt?" },
  { id: "book", en: "Did your character first become famous through books?", de: "Wurde deine Figur zuerst durch Bücher bekannt?" },
];

const relationshipIds = ["personallyKnown", "family", "parent", "sibling", "grandparent", "yourChild", "romantic", "partner", "friend", "schoolWork"];
const c = (name, icon, description, attributes) => ({
  id: name.toLowerCase().replace(/[^a-z0-9]+/g, "-"), name, icon, description,
  attributes: { ...Object.fromEntries(relationshipIds.map((id) => [id, -1])), ...attributes }
});
export const characters = [
  c("Albert Einstein", "🧑‍🔬", "The physicist who reshaped our view of space and time", { real:1, alive:-1, female:-1, scientist:1, historical:-1, european:1, american:1 }),
  c("Marie Curie", "👩‍🔬", "The pioneering scientist of radioactivity", { real:1, alive:-1, female:1, scientist:1, historical:-1, european:1 }),
  c("Leonardo da Vinci", "🎨", "Renaissance artist, thinker and inventor", { real:1, alive:-1, female:-1, scientist:1, artist:1, historical:1, european:1 }),
  c("Cleopatra", "👑", "The legendary final pharaoh of ancient Egypt", { real:1, alive:-1, female:1, politician:1, royalty:1, historical:1, european:-1 }),
  c("Napoleon Bonaparte", "🎖️", "The French emperor and military commander", { real:1, alive:-1, female:-1, politician:1, royalty:1, historical:1, european:1 }),
  c("Queen Elizabeth II", "👑", "Britain's longest-reigning monarch", { real:1, alive:-1, female:1, politician:-1, royalty:1, european:1 }),
  c("Barack Obama", "🇺🇸", "The 44th president of the United States", { real:1, alive:1, female:-1, politician:1, american:1 }),
  c("Donald Trump", "🏛️", "American president and businessman", { real:1, alive:1, female:-1, politician:1, entrepreneur:1, american:1 }),
  c("Greta Thunberg", "🌍", "The Swedish climate activist", { real:1, alive:1, female:1, politician:-1, young:1, european:1 }),
  c("Elon Musk", "🚀", "Technology entrepreneur and space-industry figure", { real:1, alive:1, female:-1, entrepreneur:1, space:1, american:1 }),
  c("Steve Jobs", "💻", "The influential co-founder of Apple", { real:1, alive:-1, female:-1, entrepreneur:1, american:1 }),
  c("MrBeast", "▶️", "The creator known for huge online challenges", { real:1, alive:1, female:-1, internet:1, american:1 }),
  c("Taylor Swift", "🎤", "The American singer-songwriter and global pop star", { real:1, alive:1, female:1, musician:1, american:1 }),
  c("Beyoncé", "🎙️", "The award-winning American singer and performer", { real:1, alive:1, female:1, musician:1, musicGroup:1, american:1 }),
  c("Michael Jackson", "🕺", "The record-breaking King of Pop", { real:1, alive:-1, female:-1, musician:1, musicGroup:1, american:1 }),
  c("Cristiano Ronaldo", "⚽", "The Portuguese football superstar", { real:1, alive:1, female:-1, athlete:1, european:1 }),
  c("Lionel Messi", "⚽", "The Argentine football legend", { real:1, alive:1, female:-1, athlete:1, american:-1, european:-1 }),
  c("Serena Williams", "🎾", "The American tennis champion", { real:1, alive:1, female:1, athlete:1, american:1 }),
  c("Harry Potter", "🧙", "The young wizard from Hogwarts", { real:-1, fictional:1, female:-1, magic:1, young:1, european:1, movie:1 }),
  c("Hermione Granger", "🪄", "The brilliant witch from Hogwarts", { real:-1, fictional:1, female:1, magic:1, young:1, european:1, movie:1 }),
  c("Elsa", "❄️", "The ice-powered queen from Frozen", { real:-1, fictional:1, female:1, magic:1, royalty:1, animated:1, powers:1, european:1, movie:1 }),
  c("Wednesday Addams", "🖤", "The wonderfully gloomy Addams daughter", { real:-1, fictional:1, female:1, young:1, american:1 }),
  c("Barbie", "💖", "The iconic fashion doll and movie heroine", { real:-1, fictional:1, female:1, animated:1, american:1, movie:1 }),
  c("Spider-Man", "🕷️", "The web-slinging hero of New York", { real:-1, fictional:1, female:-1, superhero:1, masked:1, powers:1, young:1, american:1, movie:1, red:1 }),
  c("Batman", "🦇", "Gotham's masked Dark Knight", { real:-1, fictional:1, female:-1, superhero:1, masked:1, powers:-1, american:1, movie:1 }),
  c("Superman", "🦸", "The super-powered hero from Krypton", { real:-1, fictional:1, female:-1, superhero:1, masked:-1, powers:1, nonhuman:1, space:1, american:1, movie:1, red:1 }),
  c("Wonder Woman", "⚔️", "The Amazon warrior and superhero", { real:-1, fictional:1, female:1, superhero:1, masked:-1, powers:1, american:1, movie:1, red:1 }),
  c("Darth Vader", "🌌", "The masked dark lord of the Sith", { real:-1, fictional:1, female:-1, masked:1, villain:1, powers:1, space:1, movie:1 }),
  c("Luke Skywalker", "⚔️", "The Jedi hero from a galaxy far away", { real:-1, fictional:1, female:-1, powers:1, space:1, young:1, movie:1 }),
  c("Sherlock Holmes", "🔎", "The brilliant detective of Baker Street", { real:-1, fictional:1, female:-1, detective:1, european:1, movie:1 }),
  c("Mario", "🍄", "The red-capped hero of the Mushroom Kingdom", { real:-1, fictional:1, female:-1, animated:1, game:1, powers:-1, european:1, red:1 }),
  c("Princess Peach", "👸", "The kind ruler of the Mushroom Kingdom", { real:-1, fictional:1, female:1, royalty:1, animated:1, game:1, european:1 }),
  c("Sonic the Hedgehog", "💨", "The supersonic blue video-game hero", { real:-1, fictional:1, female:-1, animated:1, game:1, powers:1, nonhuman:1 }),
  c("Pikachu", "⚡", "The electric Pokémon companion", { real:-1, fictional:1, animated:1, game:1, powers:1, electric:1, nonhuman:1, young:-1 }),
  c("Goku", "🔥", "The Saiyan martial artist from Dragon Ball", { real:-1, fictional:1, female:-1, animated:1, powers:1, nonhuman:1, space:1 }),
  c("Shrek", "🧅", "The grumpy but good-hearted green ogre", { real:-1, fictional:1, female:-1, animated:1, nonhuman:1, european:1, movie:1 }),
  c("The Joker", "🃏", "Batman's chaotic arch-enemy", { real:-1, fictional:1, female:-1, villain:1, powers:-1, american:1, movie:1 }),
  c("Mickey Mouse", "🐭", "The cheerful animated Disney icon", { real:-1, fictional:1, female:-1, animated:1, nonhuman:1, american:1, movie:1 }),
  c("Isaac Newton", "🍎", "The physicist of gravity and motion", { real:1, alive:-1, female:-1, scientist:1, historical:1, european:1 }),
  c("Stephen Hawking", "🌌", "The cosmologist who explored black holes", { real:1, alive:-1, female:-1, scientist:1, space:1, european:1 }),
  c("Nikola Tesla", "⚡", "The visionary electrical inventor", { real:1, alive:-1, female:-1, scientist:1, electric:1, european:1 }),
  c("Charles Darwin", "🐢", "The naturalist behind evolution", { real:1, alive:-1, female:-1, scientist:1, historical:1, european:1 }),
  c("Vincent van Gogh", "🌻", "The Dutch post-impressionist painter", { real:1, alive:-1, female:-1, artist:1, european:1 }),
  c("Pablo Picasso", "🖼️", "The Spanish pioneer of Cubism", { real:1, alive:-1, female:-1, artist:1, european:1 }),
  c("Frida Kahlo", "🌺", "The iconic Mexican painter", { real:1, alive:-1, female:1, artist:1, american:-1, european:-1 }),
  c("William Shakespeare", "🪶", "The playwright behind Hamlet and Macbeth", { real:1, alive:-1, female:-1, writer:1, historical:1, european:1 }),
  c("J. K. Rowling", "📚", "The author of the Harry Potter books", { real:1, alive:1, female:1, writer:1, european:1 }),
  c("Princess Diana", "👑", "The celebrated Princess of Wales", { real:1, alive:-1, female:1, royalty:1, european:1 }),
  c("Angela Merkel", "🇩🇪", "The former German chancellor", { real:1, alive:1, female:1, politician:1, european:1 }),
  c("Mahatma Gandhi", "🕊️", "The leader of India's independence movement", { real:1, alive:-1, female:-1, politician:1, european:-1, american:-1 }),
  c("Nelson Mandela", "✊", "The anti-apartheid leader and president", { real:1, alive:-1, female:-1, politician:1, european:-1, american:-1 }),
  c("Bill Gates", "💻", "The Microsoft co-founder and philanthropist", { real:1, alive:1, female:-1, entrepreneur:1, american:1 }),
  c("Mark Zuckerberg", "🌐", "The founder of Facebook", { real:1, alive:1, female:-1, entrepreneur:1, internet:1, american:1 }),
  c("Elvis Presley", "🎸", "The King of Rock and Roll", { real:1, alive:-1, female:-1, musician:1, actor:1, american:1 }),
  c("Freddie Mercury", "🎙️", "The legendary Queen frontman", { real:1, alive:-1, female:-1, musician:1, musicGroup:1, european:1 }),
  c("Adele", "🎤", "The British powerhouse vocalist", { real:1, alive:1, female:1, musician:1, european:1 }),
  c("Rihanna", "💎", "The singer and entrepreneur", { real:1, alive:1, female:1, musician:1, entrepreneur:1 }),
  c("Billie Eilish", "🟢", "The alternative pop singer-songwriter", { real:1, alive:1, female:1, musician:1, young:1, american:1 }),
  c("Eminem", "🎧", "The Detroit rap superstar", { real:1, alive:1, female:-1, musician:1, american:1 }),
  c("Ed Sheeran", "🎸", "The British singer-songwriter", { real:1, alive:1, female:-1, musician:1, european:1 }),
  c("Kylian Mbappé", "⚽", "The French football star", { real:1, alive:1, female:-1, athlete:1, football:1, european:1 }),
  c("Neymar", "⚽", "The Brazilian football star", { real:1, alive:1, female:-1, athlete:1, football:1, european:-1, american:-1 }),
  c("Michael Jordan", "🏀", "The basketball icon", { real:1, alive:1, female:-1, athlete:1, american:1 }),
  c("Usain Bolt", "🏃", "The record-breaking sprinter", { real:1, alive:1, female:-1, athlete:1, american:-1 }),
  c("PewDiePie", "▶️", "The Swedish video creator", { real:1, alive:1, female:-1, internet:1, european:1 }),
  c("Dwayne Johnson", "💪", "The actor and former wrestler", { real:1, alive:1, female:-1, actor:1, athlete:1, american:1, movie:1 }),
  c("Tom Cruise", "🎬", "The Mission: Impossible movie star", { real:1, alive:1, female:-1, actor:1, american:1, movie:1 }),
  c("Leonardo DiCaprio", "🎬", "The Oscar-winning movie actor", { real:1, alive:1, female:-1, actor:1, american:1, movie:1 }),
  c("Johnny Depp", "🏴‍☠️", "The actor known for eccentric roles", { real:1, alive:1, female:-1, actor:1, american:1, movie:1 }),
  c("Will Smith", "🎬", "The actor and rapper", { real:1, alive:1, female:-1, actor:1, musician:1, american:1, movie:1 }),
  c("Emma Watson", "🎬", "The actor and activist", { real:1, alive:1, female:1, actor:1, european:1, movie:1 }),
  c("Marilyn Monroe", "💄", "The classic Hollywood icon", { real:1, alive:-1, female:1, actor:1, american:1, movie:1 }),
  c("Lord Voldemort", "🐍", "The dark wizard of the Harry Potter stories", { real:-1, fictional:1, female:-1, magic:1, villain:1, book:1, movie:1, european:1 }),
  c("James Bond", "🎯", "The suave British secret agent", { real:-1, fictional:1, female:-1, book:1, movie:1, european:1 }),
  c("Eleven", "🩸", "The psychic hero of Stranger Things", { real:-1, fictional:1, female:1, tv:1, powers:1, young:1, american:1 }),
  c("Walter White", "⚗️", "The chemistry teacher turned crime lord", { real:-1, fictional:1, female:-1, tv:1, villain:1, american:1 }),
  c("Daenerys Targaryen", "🐉", "The dragon queen from Game of Thrones", { real:-1, fictional:1, female:1, tv:1, book:1, royalty:1, european:1 }),
  c("Jon Snow", "🐺", "The honorable hero of the North", { real:-1, fictional:1, female:-1, tv:1, book:1, european:1 }),
  c("Homer Simpson", "🍩", "The bumbling father from Springfield", { real:-1, fictional:1, female:-1, animated:1, tv:1, american:1 }),
  c("SpongeBob SquarePants", "🍍", "The cheerful sponge of Bikini Bottom", { real:-1, fictional:1, animated:1, tv:1, nonhuman:1 }),
  c("Scooby-Doo", "🐕", "The mystery-solving Great Dane", { real:-1, fictional:1, animated:1, tv:1, nonhuman:1, animal:1, detective:1, american:1 }),
  c("Bugs Bunny", "🥕", "The wisecracking cartoon rabbit", { real:-1, fictional:1, animated:1, animal:1, nonhuman:1, american:1 }),
  c("Iron Man", "🤖", "The armored genius Avenger", { real:-1, fictional:1, female:-1, superhero:1, masked:1, movie:1, american:1, red:1 }),
  c("Captain America", "🛡️", "The star-spangled super soldier", { real:-1, fictional:1, female:-1, superhero:1, powers:1, movie:1, american:1, red:1 }),
  c("Hulk", "💚", "The giant green Avenger", { real:-1, fictional:1, female:-1, superhero:1, powers:1, movie:1, american:1 }),
  c("Thor", "⚡", "The thunder god and Avenger", { real:-1, fictional:1, female:-1, superhero:1, powers:1, magic:1, movie:1, space:1 }),
  c("Deadpool", "🔴", "The wisecracking masked antihero", { real:-1, fictional:1, female:-1, superhero:1, masked:1, powers:1, movie:1, red:1 }),
  c("Thanos", "🟣", "The universe-threatening Titan", { real:-1, fictional:1, female:-1, villain:1, powers:1, movie:1, space:1, nonhuman:1 }),
  c("Yoda", "👽", "The wise Jedi master", { real:-1, fictional:1, female:-1, powers:1, movie:1, space:1, nonhuman:1 }),
  c("Jack Sparrow", "🏴‍☠️", "The eccentric pirate captain", { real:-1, fictional:1, female:-1, movie:1, european:1 }),
  c("Luigi", "👻", "Mario's green-clad brother", { real:-1, fictional:1, female:-1, animated:1, game:1, european:1 }),
  c("Link", "🗡️", "The courageous hero of Hyrule", { real:-1, fictional:1, female:-1, game:1, magic:1, young:1 }),
  c("Lara Croft", "🏹", "The adventurous archaeologist", { real:-1, fictional:1, female:1, game:1, movie:1, european:1 }),
  c("Steve (Minecraft)", "⛏️", "The block-building Minecraft hero", { real:-1, fictional:1, female:-1, game:1, animated:1 }),
  c("Kratos", "🪓", "The fierce God of War", { real:-1, fictional:1, female:-1, game:1, powers:1, red:1, european:1 }),
  c("Naruto Uzumaki", "🍥", "The ninja who dreams of leading his village", { real:-1, fictional:1, female:-1, anime:1, animated:1, powers:1, young:1 }),
  c("Monkey D. Luffy", "🏴‍☠️", "The rubber-powered pirate captain", { real:-1, fictional:1, female:-1, anime:1, animated:1, powers:1, young:1, red:1 }),
  c("Sailor Moon", "🌙", "The magical guardian of love and justice", { real:-1, fictional:1, female:1, anime:1, animated:1, magic:1, powers:1, young:1 }),
  c("Totoro", "🌳", "The gentle forest spirit", { real:-1, fictional:1, anime:1, animated:1, movie:1, magic:1, nonhuman:1 }),
  c("Godzilla", "🦖", "The colossal king of the monsters", { real:-1, fictional:1, movie:1, animal:1, nonhuman:1, powers:1 }),
  c("R2-D2", "🤖", "The brave astromech droid", { real:-1, fictional:1, robot:1, nonhuman:1, space:1, movie:1 }),
  c("Deine Mutter", "👩", "Deine Mutter oder eine mütterliche Bezugsperson", { real:1, alive:1, female:1, personallyKnown:1, family:1, parent:1 }),
  c("Dein Vater", "👨", "Dein Vater oder eine väterliche Bezugsperson", { real:1, alive:1, female:-1, personallyKnown:1, family:1, parent:1 }),
  c("Dein Bruder", "👦", "Dein Bruder", { real:1, alive:1, female:-1, personallyKnown:1, family:1, sibling:1 }),
  c("Deine Schwester", "👧", "Deine Schwester", { real:1, alive:1, female:1, personallyKnown:1, family:1, sibling:1 }),
  c("Deine Oma", "👵", "Deine Großmutter", { real:1, female:1, personallyKnown:1, family:1, grandparent:1 }),
  c("Dein Opa", "👴", "Dein Großvater", { real:1, female:-1, personallyKnown:1, family:1, grandparent:1 }),
  c("Dein Sohn", "👦", "Dein Sohn", { real:1, alive:1, female:-1, personallyKnown:1, family:1, yourChild:1, young:1 }),
  c("Deine Tochter", "👧", "Deine Tochter", { real:1, alive:1, female:1, personallyKnown:1, family:1, yourChild:1, young:1 }),
  c("Deine Freundin oder Partnerin", "💞", "Deine romantische Partnerin", { real:1, alive:1, female:1, personallyKnown:1, romantic:1, partner:1 }),
  c("Dein Freund oder Partner", "💞", "Dein romantischer Partner", { real:1, alive:1, female:-1, personallyKnown:1, romantic:1, partner:1 }),
  c("Dein Crush", "💘", "Eine Person, in die du verliebt bist", { real:1, alive:1, female:0, personallyKnown:1, romantic:1, partner:-1 }),
  c("Deine beste Freundin", "🤝", "Eine enge Freundin ohne romantische Beziehung", { real:1, alive:1, female:1, personallyKnown:1, friend:1, romantic:-1 }),
  c("Dein bester Freund", "🤝", "Ein enger Freund ohne romantische Beziehung", { real:1, alive:1, female:-1, personallyKnown:1, friend:1, romantic:-1 }),
  c("Deine Lehrerin oder Kollegin", "📚", "Eine Frau aus Schule, Ausbildung oder Arbeit", { real:1, alive:1, female:1, personallyKnown:1, schoolWork:1 }),
  c("Dein Lehrer oder Kollege", "📚", "Ein Mann aus Schule, Ausbildung oder Arbeit", { real:1, alive:1, female:-1, personallyKnown:1, schoolWork:1 }),
];
