import { featureSchema } from './feature-schema.js?v=29';
import { generateAttributeQuestions } from './generated-questions.js?v=29';

// Compatibility export for training and attribute keys. Runtime additionally
// creates evidence discriminators from the loaded database.
export const questions = generateAttributeQuestions(featureSchema);

const c = (name, icon, description, attributes) => ({
  id: name.toLowerCase().replace(/[^a-z0-9]+/g, "-"), name, icon, description,
  knownAttributes:attributes.personallyKnown === 1 || attributes.real === -1 ? questions.map(({ id }) => id) : [...new Set([...Object.keys(attributes), "personallyKnown", "fictional"])],
  attributes: { ...Object.fromEntries(questions.map(({ id }) => [id, -1])), ...attributes }
});
export const characters = [
  c("Albert Einstein", "🧑‍🔬", "The physicist who reshaped our view of space and time", { real:1, alive:-1, female:-1, scientist:1, historical:-1, european:1, american:1 }),
  c("Marie Curie", "👩‍🔬", "The pioneering scientist of radioactivity", { real:1, alive:-1, female:1, scientist:1, historical:-1, european:1 }),
  c("Leonardo da Vinci", "🎨", "Renaissance artist, thinker and inventor", { real:1, alive:-1, female:-1, scientist:1, artist:1, historical:1, european:1 }),
  c("Cleopatra", "👑", "The legendary final pharaoh of ancient Egypt", { real:1, alive:-1, female:1, politician:1, nationalLeader:1, royalty:1, historical:1, european:-1 }),
  c("Napoleon Bonaparte", "🎖️", "The French emperor and military commander", { real:1, alive:-1, female:-1, politician:1, nationalLeader:1, militaryLeader:1, royalty:1, historical:1, european:1 }),
  c("Queen Elizabeth II", "👑", "Britain's longest-reigning monarch", { real:1, alive:-1, female:1, politician:-1, royalty:1, european:1, british:1 }),
  c("Barack Obama", "🇺🇸", "The 44th president of the United States", { real:1, alive:1, female:-1, politician:1, nationalLeader:1, usPresident:1, american:1 }),
  c("Donald Trump", "🏛️", "American president and businessman", { real:1, alive:1, female:-1, politician:1, nationalLeader:1, usPresident:1, entrepreneur:1, american:1 }),
  c("Greta Thunberg", "🌍", "The Swedish climate activist", { real:1, alive:1, female:1, politician:-1, young:1, european:1 }),
  c("Elon Musk", "🚀", "Technology entrepreneur and space-industry figure", { real:1, alive:1, female:-1, entrepreneur:1, space:1, american:1 }),
  c("Steve Jobs", "💻", "The influential co-founder of Apple", { real:1, alive:-1, female:-1, entrepreneur:1, american:1 }),
  c("MrBeast", "▶️", "The creator known for huge online challenges", { real:1, alive:1, female:-1, internet:1, creator:1, american:1 }),
  c("Taylor Swift", "🎤", "The American singer-songwriter and global pop star", { real:1, alive:1, female:1, musician:1, singer:1, american:1 }),
  c("Beyoncé", "🎙️", "The award-winning American singer and performer", { real:1, alive:1, female:1, musician:1, singer:1, musicGroup:1, american:1 }),
  c("Michael Jackson", "🕺", "The record-breaking King of Pop", { real:1, alive:-1, female:-1, musician:1, singer:1, musicGroup:1, american:1 }),
  c("Cristiano Ronaldo", "⚽", "The Portuguese football superstar", { real:1, alive:1, female:-1, athlete:1, football:1, european:1 }),
  c("Lionel Messi", "⚽", "The Argentine football legend", { real:1, alive:1, female:-1, athlete:1, football:1, american:-1, european:-1 }),
  c("Serena Williams", "🎾", "The retired American tennis champion", { real:1, alive:1, female:1, athlete:1, tennis:1, retired:1, american:1 }),
  c("Harry Potter", "🧙", "The young wizard from Hogwarts", { real:-1, fictional:1, female:-1, magic:1, young:1, european:1, book:1, movie:1, protagonist:1, glasses:1 }),
  c("Hermione Granger", "🪄", "The brilliant witch from Hogwarts", { real:-1, fictional:1, female:1, magic:1, young:1, european:1, book:1, movie:1 }),
  c("Elsa", "❄️", "The ice-powered queen from Frozen", { real:-1, fictional:1, female:1, magic:1, royalty:1, animated:1, powers:1, european:1, movie:1 }),
  c("Wednesday Addams", "🖤", "The wonderfully gloomy Addams daughter", { real:-1, fictional:1, female:1, young:1, american:1 }),
  c("Barbie", "💖", "The iconic fashion doll and movie heroine", { real:-1, fictional:1, female:1, animated:1, american:1, movie:1 }),
  c("Spider-Man", "🕷️", "The web-slinging hero of New York", { real:-1, fictional:1, female:-1, superhero:1, marvel:1, masked:1, powers:1, young:1, american:1, movie:1, red:1, protagonist:1 }),
  c("Batman", "🦇", "Gotham's masked Dark Knight", { real:-1, fictional:1, female:-1, superhero:1, dc:1, masked:1, powers:-1, american:1, movie:1, protagonist:1 }),
  c("Superman", "🦸", "The super-powered hero from Krypton", { real:-1, fictional:1, female:-1, superhero:1, dc:1, masked:-1, powers:1, nonhuman:1, space:1, american:1, movie:1, red:1, protagonist:1 }),
  c("Wonder Woman", "⚔️", "The Amazon warrior and superhero", { real:-1, fictional:1, female:1, superhero:1, dc:1, masked:-1, powers:1, american:1, movie:1, red:1, protagonist:1 }),
  c("Darth Vader", "🌌", "The masked dark lord of the Sith", { real:-1, fictional:1, female:-1, starWars:1, masked:1, villain:1, powers:1, space:1, movie:1 }),
  c("Luke Skywalker", "⚔️", "The Jedi hero from a galaxy far away", { real:-1, fictional:1, female:-1, starWars:1, powers:1, space:1, young:1, movie:1, protagonist:1 }),
  c("Sherlock Holmes", "🔎", "The brilliant detective of Baker Street", { real:-1, fictional:1, female:-1, detective:1, european:1, movie:1 }),
  c("Mario", "🍄", "The red-capped hero of the Mushroom Kingdom", { real:-1, fictional:1, female:-1, animated:1, game:1, powers:-1, european:1, red:1 }),
  c("Princess Peach", "👸", "The kind ruler of the Mushroom Kingdom", { real:-1, fictional:1, female:1, royalty:1, animated:1, game:1, european:1 }),
  c("Sonic the Hedgehog", "💨", "The supersonic blue video-game hero", { real:-1, fictional:1, female:-1, animated:1, game:1, powers:1, nonhuman:1 }),
  c("Pikachu", "⚡", "The electric Pokémon companion", { real:-1, fictional:1, pokemon:1, anime:1, animated:1, game:1, powers:1, electric:1, nonhuman:1, young:-1 }),
  c("Goku", "🔥", "The Saiyan martial artist from Dragon Ball", { real:-1, fictional:1, female:-1, anime:1, animated:1, powers:1, nonhuman:1, space:1, protagonist:1 }),
  c("Shrek", "🧅", "The grumpy but good-hearted green ogre", { real:-1, fictional:1, female:-1, animated:1, nonhuman:1, european:1, movie:1 }),
  c("The Joker", "🃏", "Batman's chaotic arch-enemy", { real:-1, fictional:1, female:-1, villain:1, powers:-1, american:1, movie:1 }),
  c("Mickey Mouse", "🐭", "The cheerful animated Disney icon", { real:-1, fictional:1, female:-1, animated:1, nonhuman:1, american:1, movie:1 }),
  c("Isaac Newton", "🍎", "The physicist of gravity and motion", { real:1, alive:-1, female:-1, scientist:1, historical:1, european:1 }),
  c("Stephen Hawking", "🌌", "The cosmologist who explored black holes", { real:1, alive:-1, female:-1, scientist:1, space:1, european:1 }),
  c("Nikola Tesla", "⚡", "The visionary electrical inventor", { real:1, alive:-1, female:-1, scientist:1, electric:1, european:1 }),
  c("Charles Darwin", "🐢", "The naturalist behind evolution", { real:1, alive:-1, female:-1, scientist:1, historical:1, european:1 }),
  c("Vincent van Gogh", "🌻", "The Dutch post-impressionist painter", { real:1, alive:-1, female:-1, artist:1, european:1 }),
  c("Pablo Picasso", "🖼️", "The Spanish pioneer of Cubism", { real:1, alive:-1, female:-1, artist:1, european:1 }),
  c("Frida Kahlo", "🌺", "The iconic Mexican painter", { real:1, alive:-1, female:1, artist:1, american:-1, european:-1 }),
  c("William Shakespeare", "🪶", "The playwright behind Hamlet and Macbeth", { real:1, alive:-1, female:-1, writer:1, historical:1, european:1 }),
  c("J. K. Rowling", "📚", "The author of the Harry Potter books", { real:1, alive:1, female:1, writer:1, european:1 }),
  c("Princess Diana", "👑", "The celebrated Princess of Wales", { real:1, alive:-1, female:1, royalty:1, european:1 }),
  c("Angela Merkel", "🇩🇪", "The former German chancellor", { real:1, alive:1, female:1, politician:1, nationalLeader:1, european:1 }),
  c("Mahatma Gandhi", "🕊️", "The leader of India's independence movement", { real:1, alive:-1, female:-1, politician:1, activist:1, european:-1, american:-1 }),
  c("Nelson Mandela", "✊", "The anti-apartheid leader and president", { real:1, alive:-1, female:-1, politician:1, nationalLeader:1, activist:1, european:-1, american:-1 }),
  c("Bill Gates", "💻", "The Microsoft co-founder and philanthropist", { real:1, alive:1, female:-1, entrepreneur:1, american:1 }),
  c("Mark Zuckerberg", "🌐", "The founder of Facebook", { real:1, alive:1, female:-1, entrepreneur:1, internet:1, american:1 }),
  c("Elvis Presley", "🎸", "The King of Rock and Roll", { real:1, alive:-1, female:-1, musician:1, actor:1, american:1 }),
  c("Freddie Mercury", "🎙️", "The legendary Queen frontman", { real:1, alive:-1, female:-1, musician:1, musicGroup:1, european:1 }),
  c("Adele", "🎤", "The British powerhouse vocalist", { real:1, alive:1, female:1, musician:1, european:1 }),
  c("Rihanna", "💎", "The singer and entrepreneur", { real:1, alive:1, female:1, musician:1, entrepreneur:1 }),
  c("Billie Eilish", "🟢", "The alternative pop singer-songwriter", { real:1, alive:1, female:1, musician:1, young:1, american:1 }),
  c("Eminem", "🎧", "The Detroit rap superstar", { real:1, alive:1, female:-1, musician:1, american:1 }),
  c("Ed Sheeran", "🎸", "The British singer-songwriter", { real:1, alive:1, female:-1, musician:1, european:1 }),
  c("Kylian Mbappé", "⚽", "The French football star", { real:1, alive:1, female:-1, athlete:1, football:1, european:1 }),
  c("Neymar", "⚽", "The Brazilian football star", { real:1, alive:1, female:-1, athlete:1, football:1, european:-1, american:-1 }),
  c("Michael Jordan", "🏀", "The retired basketball icon", { real:1, alive:1, female:-1, athlete:1, basketball:1, retired:1, american:1 }),
  c("Usain Bolt", "🏃", "The retired record-breaking sprinter", { real:1, alive:1, female:-1, athlete:1, runner:1, retired:1, american:-1 }),
  c("PewDiePie", "▶️", "The Swedish video creator", { real:1, alive:1, female:-1, internet:1, european:1 }),
  c("Dwayne Johnson", "💪", "The actor and former wrestler", { real:1, alive:1, female:-1, actor:1, athlete:1, american:1, movie:1 }),
  c("Tom Cruise", "🎬", "The Mission: Impossible movie star", { real:1, alive:1, female:-1, actor:1, american:1, movie:1 }),
  c("Leonardo DiCaprio", "🎬", "The Oscar-winning movie actor", { real:1, alive:1, female:-1, actor:1, american:1, movie:1 }),
  c("Johnny Depp", "🏴‍☠️", "The actor known for eccentric roles", { real:1, alive:1, female:-1, actor:1, american:1, movie:1 }),
  c("Will Smith", "🎬", "The actor and rapper", { real:1, alive:1, female:-1, actor:1, musician:1, american:1, movie:1 }),
  c("Emma Watson", "🎬", "The actor and activist", { real:1, alive:1, female:1, actor:1, european:1, movie:1 }),
  c("Marilyn Monroe", "💄", "The classic Hollywood icon", { real:1, alive:-1, female:1, actor:1, american:1, movie:1 }),
  c("Lord Voldemort", "🐍", "The dark wizard of the Harry Potter stories", { real:-1, fictional:1, female:-1, magic:1, villain:1, book:1, movie:1, european:1 }),
  c("James Bond", "🎯", "The suave British secret agent", { real:-1, fictional:1, female:-1, book:1, movie:1, european:1 }),
  c("Eleven", "🩸", "The psychic hero of Stranger Things", { real:-1, fictional:1, female:1, tv:1, powers:1, young:1, american:1 }),
  c("Walter White", "⚗️", "The chemistry teacher turned crime lord", { real:-1, fictional:1, female:-1, tv:1, villain:1, american:1 }),
  c("Daenerys Targaryen", "🐉", "The dragon queen from Game of Thrones", { real:-1, fictional:1, female:1, tv:1, book:1, royalty:1, european:1 }),
  c("Jon Snow", "🐺", "The honorable hero of the North", { real:-1, fictional:1, female:-1, tv:1, book:1, european:1 }),
  c("Homer Simpson", "🍩", "The bumbling father from Springfield", { real:-1, fictional:1, female:-1, animated:1, tv:1, american:1 }),
  c("SpongeBob SquarePants", "🍍", "The cheerful sponge of Bikini Bottom", { real:-1, fictional:1, animated:1, tv:1, nonhuman:1 }),
  c("Scooby-Doo", "🐕", "The mystery-solving Great Dane", { real:-1, fictional:1, animated:1, tv:1, nonhuman:1, animal:1, detective:1, american:1 }),
  c("Bugs Bunny", "🥕", "The wisecracking cartoon rabbit", { real:-1, fictional:1, animated:1, animal:1, nonhuman:1, american:1 }),
  c("Iron Man", "🤖", "The armored genius Avenger", { real:-1, fictional:1, female:-1, superhero:1, masked:1, movie:1, american:1, red:1 }),
  c("Captain America", "🛡️", "The star-spangled super soldier", { real:-1, fictional:1, female:-1, superhero:1, powers:1, movie:1, american:1, red:1 }),
  c("Hulk", "💚", "The giant green Avenger", { real:-1, fictional:1, female:-1, superhero:1, powers:1, movie:1, american:1 }),
  c("Thor", "⚡", "The thunder god and Avenger", { real:-1, fictional:1, female:-1, superhero:1, powers:1, magic:1, movie:1, space:1 }),
  c("Deadpool", "🔴", "The wisecracking masked antihero", { real:-1, fictional:1, female:-1, superhero:1, masked:1, powers:1, movie:1, red:1 }),
  c("Thanos", "🟣", "The universe-threatening Titan", { real:-1, fictional:1, female:-1, villain:1, powers:1, movie:1, space:1, nonhuman:1 }),
  c("Yoda", "👽", "The wise Jedi master", { real:-1, fictional:1, female:-1, powers:1, movie:1, space:1, nonhuman:1 }),
  c("Jack Sparrow", "🏴‍☠️", "The eccentric pirate captain", { real:-1, fictional:1, female:-1, movie:1, european:1 }),
  c("Luigi", "👻", "Mario's green-clad brother", { real:-1, fictional:1, female:-1, animated:1, game:1, european:1 }),
  c("Link", "🗡️", "The courageous hero of Hyrule", { real:-1, fictional:1, female:-1, game:1, magic:1, young:1 }),
  c("Lara Croft", "🏹", "The adventurous archaeologist", { real:-1, fictional:1, female:1, game:1, movie:1, european:1 }),
  c("Steve (Minecraft)", "⛏️", "The block-building Minecraft hero", { real:-1, fictional:1, female:-1, game:1, animated:1 }),
  c("Kratos", "🪓", "The fierce God of War", { real:-1, fictional:1, female:-1, game:1, powers:1, red:1, european:1 }),
  c("Naruto Uzumaki", "🍥", "The ninja who dreams of leading his village", { real:-1, fictional:1, female:-1, anime:1, animated:1, powers:1, young:1 }),
  c("Monkey D. Luffy", "🏴‍☠️", "The rubber-powered pirate captain", { real:-1, fictional:1, female:-1, anime:1, animated:1, powers:1, young:1, red:1 }),
  c("Sailor Moon", "🌙", "The magical guardian of love and justice", { real:-1, fictional:1, female:1, anime:1, animated:1, magic:1, powers:1, young:1 }),
  c("Totoro", "🌳", "The gentle forest spirit", { real:-1, fictional:1, anime:1, animated:1, movie:1, magic:1, nonhuman:1 }),
  c("Godzilla", "🦖", "The colossal king of the monsters", { real:-1, fictional:1, movie:1, animal:1, nonhuman:1, powers:1 }),
  c("R2-D2", "🤖", "The brave astromech droid", { real:-1, fictional:1, robot:1, nonhuman:1, space:1, movie:1 }),
  c("Deine Mutter", "👩", "Deine Mutter oder eine mütterliche Bezugsperson", { real:1, alive:1, female:1, personallyKnown:1, family:1, parent:1 }),
  c("Dein Vater", "👨", "Dein Vater oder eine väterliche Bezugsperson", { real:1, alive:1, female:-1, personallyKnown:1, family:1, parent:1 }),
  c("Dein Bruder", "👦", "Dein Bruder", { real:1, alive:1, female:-1, personallyKnown:1, family:1, sibling:1 }),
  c("Deine Schwester", "👧", "Deine Schwester", { real:1, alive:1, female:1, personallyKnown:1, family:1, sibling:1 }),
  c("Deine Oma", "👵", "Deine Großmutter", { real:1, female:1, personallyKnown:1, family:1, grandparent:1 }),
  c("Dein Opa", "👴", "Dein Großvater", { real:1, female:-1, personallyKnown:1, family:1, grandparent:1 }),
  c("Dein Sohn", "👦", "Dein Sohn", { real:1, alive:1, female:-1, personallyKnown:1, family:1, yourChild:1, young:1 }),
  c("Deine Tochter", "👧", "Deine Tochter", { real:1, alive:1, female:1, personallyKnown:1, family:1, yourChild:1, young:1 }),
  c("Deine Freundin oder Partnerin", "💞", "Deine romantische Partnerin", { real:1, alive:1, female:1, personallyKnown:1, romantic:1, partner:1 }),
  c("Dein Freund oder Partner", "💞", "Dein romantischer Partner", { real:1, alive:1, female:-1, personallyKnown:1, romantic:1, partner:1 }),
  c("Dein Crush", "💘", "Eine Person, in die du verliebt bist", { real:1, alive:1, female:0, personallyKnown:1, romantic:1, partner:-1 }),
  c("Deine beste Freundin", "🤝", "Eine enge Freundin ohne romantische Beziehung", { real:1, alive:1, female:1, personallyKnown:1, friend:1, bestFriend:1, romantic:-1 }),
  c("Dein bester Freund", "🤝", "Ein enger Freund ohne romantische Beziehung", { real:1, alive:1, female:-1, personallyKnown:1, friend:1, bestFriend:1, romantic:-1 }),
  c("Deine Lehrerin oder Kollegin", "📚", "Eine Frau aus Schule, Ausbildung oder Arbeit", { real:1, alive:1, female:1, personallyKnown:1, schoolWork:1 }),
  c("Dein Lehrer oder Kollege", "📚", "Ein Mann aus Schule, Ausbildung oder Arbeit", { real:1, alive:1, female:-1, personallyKnown:1, schoolWork:1 }),
  c("Deine Tante", "👩", "Deine Tante", { real:1, alive:1, female:1, personallyKnown:1, family:1, auntUncle:1 }),
  c("Dein Onkel", "👨", "Dein Onkel", { real:1, alive:1, female:-1, personallyKnown:1, family:1, auntUncle:1 }),
  c("Deine Cousine", "👩", "Deine Cousine", { real:1, alive:1, female:1, personallyKnown:1, family:1, cousin:1 }),
  c("Dein Cousin", "👨", "Dein Cousin", { real:1, alive:1, female:-1, personallyKnown:1, family:1, cousin:1 }),
  c("Deine Nichte", "👧", "Deine Nichte", { real:1, alive:1, female:1, personallyKnown:1, family:1, nieceNephew:1 }),
  c("Dein Neffe", "👦", "Dein Neffe", { real:1, alive:1, female:-1, personallyKnown:1, family:1, nieceNephew:1 }),
  c("Deine Stiefmutter", "👩", "Deine Stiefmutter", { real:1, alive:1, female:1, personallyKnown:1, family:1, parent:1, stepParent:1 }),
  c("Dein Stiefvater", "👨", "Dein Stiefvater", { real:1, alive:1, female:-1, personallyKnown:1, family:1, parent:1, stepParent:1 }),
  c("Deine Ehefrau", "💍", "Deine Ehefrau", { real:1, alive:1, female:1, personallyKnown:1, romantic:1, partner:1, spouse:1 }),
  c("Dein Ehemann", "💍", "Dein Ehemann", { real:1, alive:1, female:-1, personallyKnown:1, romantic:1, partner:1, spouse:1 }),
  c("Deine Ex-Partnerin", "💔", "Eine frühere Partnerin", { real:1, alive:1, female:1, personallyKnown:1, exPartner:1 }),
  c("Dein Ex-Partner", "💔", "Ein früherer Partner", { real:1, alive:1, female:-1, personallyKnown:1, exPartner:1 }),
  c("Deine Freundin", "🤝", "Eine Freundin ohne romantische Beziehung", { real:1, alive:1, female:1, personallyKnown:1, friend:1 }),
  c("Dein Freund", "🤝", "Ein Freund ohne romantische Beziehung", { real:1, alive:1, female:-1, personallyKnown:1, friend:1 }),
  c("Deine Nachbarin", "🏠", "Deine Nachbarin", { real:1, alive:1, female:1, personallyKnown:1, neighbor:1 }),
  c("Dein Nachbar", "🏠", "Dein Nachbar", { real:1, alive:1, female:-1, personallyKnown:1, neighbor:1 }),
  c("Deine Mitbewohnerin", "🏠", "Deine Mitbewohnerin", { real:1, alive:1, female:1, personallyKnown:1, roommate:1 }),
  c("Dein Mitbewohner", "🏠", "Dein Mitbewohner", { real:1, alive:1, female:-1, personallyKnown:1, roommate:1 }),
  c("Deine Lehrerin", "📚", "Deine Lehrerin", { real:1, alive:1, female:1, personallyKnown:1, schoolWork:1, teacher:1 }),
  c("Dein Lehrer", "📚", "Dein Lehrer", { real:1, alive:1, female:-1, personallyKnown:1, schoolWork:1, teacher:1 }),
  c("Deine Kollegin", "💼", "Deine Kollegin", { real:1, alive:1, female:1, personallyKnown:1, schoolWork:1, coworker:1 }),
  c("Dein Kollege", "💼", "Dein Kollege", { real:1, alive:1, female:-1, personallyKnown:1, schoolWork:1, coworker:1 }),
  c("Deine Chefin", "💼", "Deine Chefin", { real:1, alive:1, female:1, personallyKnown:1, schoolWork:1, boss:1 }),
  c("Dein Chef", "💼", "Dein Chef", { real:1, alive:1, female:-1, personallyKnown:1, schoolWork:1, boss:1 }),
  c("Deine Mitschülerin", "🎒", "Deine Mitschülerin", { real:1, alive:1, female:1, personallyKnown:1, schoolWork:1, classmate:1 }),
  c("Dein Mitschüler", "🎒", "Dein Mitschüler", { real:1, alive:1, female:-1, personallyKnown:1, schoolWork:1, classmate:1 }),
];

const p = (name, icon, description, attributes = {}) => c(name, icon, description, { real:1, alive:1, ...attributes });
const f = (name, icon, description, attributes = {}) => c(name, icon, description, { real:-1, fictional:1, ...attributes });

characters.push(
  p("Lady Gaga","🎤","US-amerikanische Sängerin und Schauspielerin",{female:1,musician:1,singer:1,actor:1,american:1,movie:1}),
  p("Ariana Grande","🎤","US-amerikanische Popsängerin",{female:1,musician:1,singer:1,actor:1,american:1}),
  p("Selena Gomez","🎤","Sängerin und Schauspielerin",{female:1,musician:1,singer:1,actor:1,american:1,tv:1}),
  p("Justin Bieber","🎤","Kanadischer Popsänger",{musician:1,singer:1,internet:1}),
  p("Drake","🎧","Kanadischer Rapper und Sänger",{musician:1,rapper:1,actor:1}),
  p("Kanye West","🎧","US-amerikanischer Rapper und Produzent",{musician:1,rapper:1,american:1}),
  p("Snoop Dogg","🎧","US-amerikanischer Rapper",{musician:1,rapper:1,american:1}),
  p("Tupac Shakur","🎧","Einflussreicher US-Rapper",{alive:-1,musician:1,rapper:1,american:1}),
  p("Whitney Houston","🎤","US-amerikanische Ausnahmesängerin",{alive:-1,female:1,musician:1,singer:1,actor:1,american:1}),
  p("Madonna","🎤","US-amerikanische Popikone",{female:1,musician:1,singer:1,actor:1,american:1}),
  p("Britney Spears","🎤","US-amerikanische Popsängerin",{female:1,musician:1,singer:1,american:1,blonde:1}),
  p("Bruno Mars","🎤","US-amerikanischer Sänger und Entertainer",{musician:1,singer:1,american:1}),
  p("Dua Lipa","🎤","Britisch-albanische Popsängerin",{female:1,musician:1,singer:1,european:1}),
  p("Shakira","🎤","Kolumbianische Sängerin",{female:1,musician:1,singer:1}),
  p("Bad Bunny","🎧","Puerto-ricanischer Sänger und Rapper",{musician:1,rapper:1,singer:1}),
  p("The Weeknd","🎤","Kanadischer R&B-Sänger",{musician:1,singer:1}),
  p("Post Malone","🎤","US-amerikanischer Sänger und Rapper",{musician:1,singer:1,rapper:1,american:1}),
  p("Miley Cyrus","🎤","US-amerikanische Sängerin und Schauspielerin",{female:1,musician:1,singer:1,actor:1,american:1}),
  p("Olivia Rodrigo","🎤","US-amerikanische Sängerin und Schauspielerin",{female:1,musician:1,singer:1,actor:1,american:1,young:1}),
  p("Harry Styles","🎤","Britischer Sänger und Schauspieler",{musician:1,singer:1,musicGroup:1,actor:1,european:1}),
  p("Zendaya","🎬","US-amerikanische Schauspielerin und Sängerin",{female:1,actor:1,musician:1,singer:1,american:1,movie:1,tv:1}),
  p("Scarlett Johansson","🎬","US-amerikanische Filmschauspielerin",{female:1,actor:1,american:1,movie:1,marvel:1}),
  p("Robert Downey Jr.","🎬","US-amerikanischer Schauspieler",{actor:1,american:1,movie:1,marvel:1}),
  p("Chris Hemsworth","🎬","Australischer Schauspieler",{actor:1,movie:1,marvel:1,blonde:1}),
  p("Chris Evans","🎬","US-amerikanischer Schauspieler",{actor:1,american:1,movie:1,marvel:1}),
  p("Margot Robbie","🎬","Australische Schauspielerin",{female:1,actor:1,movie:1,dc:1,blonde:1}),
  p("Jenna Ortega","🎬","US-amerikanische Schauspielerin",{female:1,actor:1,american:1,tv:1,horror:1,young:1}),
  p("Ryan Reynolds","🎬","Kanadischer Schauspieler",{actor:1,movie:1,marvel:1,comedian:1}),
  p("Jim Carrey","😂","Kanadischer Komiker und Schauspieler",{actor:1,comedian:1,movie:1}),
  p("Adam Sandler","😂","US-amerikanischer Komiker und Schauspieler",{actor:1,comedian:1,movie:1,american:1}),
  p("Arnold Schwarzenegger","🎬","Schauspieler und ehemaliger Bodybuilder",{actor:1,athlete:1,politician:1,movie:1,american:1,european:1}),
  p("Jackie Chan","🥋","Hongkonger Actionstar und Kampfkünstler",{actor:1,athlete:1,movie:1}),
  p("Tom Hanks","🎬","US-amerikanischer Filmschauspieler",{actor:1,movie:1,american:1}),
  p("Brad Pitt","🎬","US-amerikanischer Filmschauspieler",{actor:1,movie:1,american:1,blonde:1}),
  p("Angelina Jolie","🎬","US-amerikanische Schauspielerin",{female:1,actor:1,movie:1,american:1}),
  p("Meryl Streep","🎬","US-amerikanische Schauspielerin",{female:1,actor:1,movie:1,american:1}),
  p("Samuel L. Jackson","🎬","US-amerikanischer Schauspieler",{actor:1,movie:1,american:1,marvel:1}),
  p("Daniel Radcliffe","🎬","Britischer Schauspieler",{actor:1,movie:1,european:1,glasses:1}),
  p("Robert Pattinson","🎬","Britischer Schauspieler",{actor:1,movie:1,european:1,dc:1}),
  p("Gal Gadot","🎬","Israelische Schauspielerin",{female:1,actor:1,movie:1,dc:1}),
  p("LeBron James","🏀","US-amerikanischer Basketballstar",{athlete:1,basketball:1,american:1}),
  p("Kobe Bryant","🏀","US-amerikanische Basketballlegende",{alive:-1,athlete:1,basketball:1,american:1}),
  p("Stephen Curry","🏀","US-amerikanischer Basketballstar",{athlete:1,basketball:1,american:1}),
  p("Roger Federer","🎾","Schweizer Tennislegende",{athlete:1,tennis:1,european:1}),
  p("Rafael Nadal","🎾","Spanische Tennislegende",{athlete:1,tennis:1,european:1}),
  p("Novak Djokovic","🎾","Serbischer Tennisstar",{athlete:1,tennis:1,european:1}),
  p("Lewis Hamilton","🏎️","Britischer Formel-1-Weltmeister",{athlete:1,motorsport:1,european:1}),
  p("Michael Schumacher","🏎️","Deutsche Formel-1-Legende",{athlete:1,motorsport:1,european:1}),
  p("Max Verstappen","🏎️","Niederländischer Formel-1-Weltmeister",{athlete:1,motorsport:1,european:1}),
  p("Tiger Woods","⛳","US-amerikanische Golflegende",{athlete:1,american:1}),
  p("Simone Biles","🤸","US-amerikanische Turnerin",{female:1,athlete:1,american:1}),
  p("Zlatan Ibrahimović","⚽","Schwedischer Fußballstar",{athlete:1,football:1,european:1}),
  p("Erling Haaland","⚽","Norwegischer Fußballstar",{athlete:1,football:1,european:1,blonde:1}),
  p("Mohamed Salah","⚽","Ägyptischer Fußballstar",{athlete:1,football:1,european:1}),
  p("Alex Morgan","⚽","US-amerikanische Fußballspielerin",{female:1,athlete:1,football:1,american:1}),
  p("Winston Churchill","🏛️","Britischer Premierminister im Zweiten Weltkrieg",{alive:-1,politician:1,nationalLeader:1,european:1}),
  p("Abraham Lincoln","🏛️","16. Präsident der USA",{alive:-1,politician:1,nationalLeader:1,usPresident:1,american:1}),
  p("George Washington","🏛️","Erster Präsident der USA",{alive:-1,politician:1,nationalLeader:1,usPresident:1,militaryLeader:1,american:1,historical:1}),
  p("Martin Luther King Jr.","🕊️","US-amerikanischer Bürgerrechtler",{alive:-1,politician:1,activist:1,american:1}),
  p("Anne Frank","📖","Deutsch-jüdische Tagebuchautorin",{alive:-1,female:1,writer:1,european:1,young:1}),
  p("Wolfgang Amadeus Mozart","🎼","Österreichischer Komponist",{alive:-1,musician:1,historical:1,european:1}),
  p("Ludwig van Beethoven","🎼","Deutscher Komponist",{alive:-1,musician:1,european:1}),
  p("Johann Sebastian Bach","🎼","Deutscher Barockkomponist",{alive:-1,musician:1,historical:1,european:1}),
  p("Kai Cenat","📱","US-amerikanischer Streamer",{internet:1,creator:1,american:1}),
  p("IShowSpeed","📱","US-amerikanischer Streamer",{internet:1,creator:1,american:1,young:1}),
  p("Logan Paul","📱","US-amerikanischer Creator und Wrestler",{internet:1,creator:1,athlete:1,american:1}),
  p("Charli D'Amelio","📱","US-amerikanische Social-Media-Creatorin",{female:1,internet:1,creator:1,american:1,young:1}),
  p("Khaby Lame","📱","Senegalesisch-italienischer Social-Media-Creator",{internet:1,creator:1,european:1}),
  p("Kylie Jenner","💄","US-amerikanische Unternehmerin und Influencerin",{female:1,internet:1,creator:1,model:1,entrepreneur:1,american:1}),
  p("Gordon Ramsay","👨‍🍳","Britischer Starkoch und TV-Persönlichkeit",{tv:1,european:1}),
  p("Quentin Tarantino","🎥","US-amerikanischer Filmregisseur",{director:1,writer:1,movie:1,american:1}),
  p("Steven Spielberg","🎥","US-amerikanischer Filmregisseur",{director:1,movie:1,american:1,glasses:1}),
  p("Christopher Nolan","🎥","Britisch-amerikanischer Filmregisseur",{director:1,writer:1,movie:1,european:1}),

  f("Black Panther","🐆","Marvel-Held und König von Wakanda",{male:1,superhero:1,marvel:1,movie:1,powers:1,protagonist:1}),
  f("Doctor Strange","🌀","Marvels Meister der mystischen Künste",{superhero:1,marvel:1,movie:1,magic:1,powers:1,protagonist:1}),
  f("Wolverine","🦡","Marvel-Mutant mit Adamantiumkrallen",{superhero:1,marvel:1,movie:1,powers:1,protagonist:1}),
  f("Black Widow","🕷️","Marvel-Agentin und Avenger",{female:1,superhero:1,marvel:1,movie:1,protagonist:1}),
  f("Scarlet Witch","🔮","Magiebegabte Marvel-Heldin",{female:1,superhero:1,marvel:1,movie:1,magic:1,powers:1,red:1}),
  f("Loki","🐍","Trickreicher Gott aus dem Marvel-Universum",{marvel:1,movie:1,tv:1,magic:1,powers:1,villain:1}),
  f("Groot","🌳","Baumartiger Guardian der Galaxie",{marvel:1,movie:1,space:1,powers:1,nonhuman:1}),
  f("Aquaman","🔱","DC-Held und König von Atlantis",{superhero:1,dc:1,movie:1,powers:1,royalty:1,protagonist:1}),
  f("The Flash","⚡","Rasend schneller DC-Superheld",{superhero:1,dc:1,movie:1,tv:1,powers:1,red:1}),
  f("Harley Quinn","♦️","Chaotische DC-Antiheldin",{female:1,dc:1,movie:1,villain:1}),
  f("Catwoman","🐈","Gothams berühmte Meisterdiebin",{female:1,dc:1,movie:1,masked:1}),
  f("Green Lantern","💚","Kosmischer DC-Superheld",{superhero:1,dc:1,movie:1,space:1,powers:1}),
  f("Robin","🐦","Batmans junger Partner",{superhero:1,dc:1,masked:1,young:1,red:1}),
  f("Maleficent","🐉","Mächtige Disney-Zauberin",{female:1,disney:1,movie:1,magic:1,powers:1,villain:1}),
  f("Moana","🌊","Disney-Heldin auf großer Seereise",{female:1,disney:1,animated:1,movie:1,young:1,protagonist:1}),
  f("Aladdin","🪔","Disney-Held aus Agrabah",{disney:1,animated:1,movie:1,magic:1,young:1,protagonist:1}),
  f("Ariel","🧜‍♀️","Die kleine Meerjungfrau",{female:1,disney:1,animated:1,movie:1,princess:1,royalty:1,nonhuman:1,red:1}),
  f("Cinderella","👠","Disney-Prinzessin mit gläsernem Schuh",{female:1,disney:1,animated:1,movie:1,princess:1,magic:1,blonde:1}),
  f("Snow White","🍎","Disney-Prinzessin aus dem Märchen",{female:1,disney:1,animated:1,movie:1,princess:1,young:1}),
  f("Rapunzel","🌸","Langhaarige Disney-Prinzessin",{female:1,disney:1,animated:1,movie:1,princess:1,magic:1,blonde:1}),
  f("Mulan","⚔️","Disney-Kriegerin aus China",{female:1,disney:1,animated:1,movie:1,protagonist:1}),
  f("Simba","🦁","König der Löwen",{disney:1,animated:1,movie:1,animal:1,nonhuman:1,royalty:1,protagonist:1}),
  f("Stitch","👽","Blaues außerirdisches Disney-Experiment",{disney:1,animated:1,movie:1,space:1,nonhuman:1}),
  f("Olaf","⛄","Fröhlicher Schneemann aus Frozen",{disney:1,animated:1,movie:1,magic:1,nonhuman:1}),
  f("Minnie Mouse","🐭","Mickys berühmte Freundin",{female:1,disney:1,animated:1,animal:1,nonhuman:1}),
  f("Donald Duck","🦆","Temperamentvolle Disney-Ente",{disney:1,animated:1,animal:1,nonhuman:1}),
  f("Han Solo","🚀","Schmuggler und Held der Rebellion",{starWars:1,movie:1,space:1,protagonist:1}),
  f("Princess Leia","👑","Prinzessin und Anführerin der Rebellion",{female:1,starWars:1,movie:1,space:1,royalty:1,protagonist:1}),
  f("Obi-Wan Kenobi","⚔️","Weiser Jedi-Meister",{starWars:1,movie:1,tv:1,space:1,powers:1}),
  f("The Mandalorian","🪖","Maskierter Kopfgeldjäger aus Star Wars",{starWars:1,tv:1,space:1,masked:1,hat:1,protagonist:1}),
  f("Grogu","💚","Machtbegabtes Kind aus Star Wars",{starWars:1,tv:1,space:1,powers:1,nonhuman:1,young:1}),
  f("Chewbacca","🐻","Treuer Wookiee und Pilot",{starWars:1,movie:1,space:1,nonhuman:1}),
  f("C-3PO","🤖","Goldener Protokolldroide",{starWars:1,movie:1,space:1,robot:1,nonhuman:1}),
  f("Ash Ketchum","🧢","Pokémon-Trainer aus Alabastia",{pokemon:1,anime:1,animated:1,young:1,hat:1,protagonist:1}),
  f("Charizard","🐉","Feuerfliegendes Pokémon",{pokemon:1,anime:1,game:1,animated:1,animal:1,nonhuman:1,powers:1}),
  f("Mewtwo","🧬","Legendäres Psycho-Pokémon",{pokemon:1,anime:1,game:1,animated:1,nonhuman:1,powers:1}),
  f("Team Rocket","🚀","Pokémon-Gaunertrio",{pokemon:1,anime:1,animated:1,villain:1}),
  f("Vegeta","🔥","Stolzer Saiyajin-Prinz",{anime:1,animated:1,powers:1,space:1,royalty:1}),
  f("Sasuke Uchiha","⚡","Narutos rivalisierender Ninja",{anime:1,animated:1,powers:1,young:1}),
  f("Kakashi Hatake","🥷","Legendärer Ninja-Lehrer",{anime:1,animated:1,powers:1,masked:1}),
  f("Tanjiro Kamado","🗡️","Dämonenjäger mit gutem Herzen",{anime:1,animated:1,powers:1,young:1,protagonist:1}),
  f("Nezuko Kamado","🌸","Dämonische Schwester von Tanjiro",{female:1,anime:1,animated:1,powers:1,young:1,nonhuman:1}),
  f("Satoru Gojo","👓","Extrem mächtiger Jujutsu-Lehrer",{anime:1,animated:1,powers:1,masked:1}),
  f("Light Yagami","📓","Besitzer des Death Note",{anime:1,animated:1,villain:1,young:1,protagonist:1}),
  f("Eren Yeager","⚔️","Titanenwandler aus Attack on Titan",{anime:1,animated:1,powers:1,young:1,protagonist:1}),
  f("Deku","💥","Junger Held aus My Hero Academia",{anime:1,animated:1,superhero:1,powers:1,young:1,protagonist:1}),
  f("Geralt of Rivia","⚔️","Monsterjäger aus The Witcher",{game:1,book:1,tv:1,magic:1,powers:1,protagonist:1}),
  f("Master Chief","🪖","Gepanzerter Supersoldat aus Halo",{game:1,space:1,masked:1,hat:1,protagonist:1}),
  f("Samus Aran","🚀","Gepanzerte Weltraum-Kopfgeldjägerin",{female:1,game:1,space:1,masked:1,hat:1,protagonist:1}),
  f("Zelda","👑","Prinzessin des Königreichs Hyrule",{female:1,game:1,magic:1,princess:1,royalty:1,blonde:1}),
  f("Kirby","🌸","Rosa Held mit Kopierfähigkeiten",{game:1,animated:1,powers:1,nonhuman:1,protagonist:1}),
  f("Donkey Kong","🦍","Starker Videospiel-Gorilla",{game:1,animated:1,animal:1,nonhuman:1,protagonist:1}),
  f("Bowser","🐢","Marios feuerspeiender Erzfeind",{game:1,animated:1,animal:1,nonhuman:1,villain:1,royalty:1,powers:1}),
  f("Yoshi","🦖","Marios freundlicher Dinosaurier",{game:1,animated:1,animal:1,nonhuman:1,protagonist:1}),
  f("Crash Bandicoot","🌀","Wirbelnder Videospiel-Beuteldachs",{game:1,animated:1,animal:1,nonhuman:1,protagonist:1}),
  f("Pac-Man","🟡","Gelbe Videospiel-Ikone",{game:1,animated:1,nonhuman:1,protagonist:1}),
  f("Solid Snake","📦","Legendärer Videospiel-Agent",{game:1,masked:-1,protagonist:1}),
  f("Arthur Morgan","🤠","Outlaw aus Red Dead Redemption",{game:1,hat:1,protagonist:1,american:1}),
  f("Michael Myers","🔪","Maskierter Horrorfilm-Killer",{movie:1,horror:1,masked:1,villain:1}),
  f("Freddy Krueger","🔥","Traum-Killer mit Klingenhandschuh",{movie:1,horror:1,hat:1,villain:1,powers:1}),
  f("Jason Voorhees","🏒","Maskierter Killer vom Crystal Lake",{movie:1,horror:1,masked:1,villain:1}),
  f("Ghostface","👻","Maskierter Killer aus Scream",{movie:1,horror:1,masked:1,villain:1}),
  f("Pennywise","🎈","Gestaltwandelnder Horrorclown",{movie:1,book:1,horror:1,villain:1,powers:1,nonhuman:1}),
  f("Dracula","🧛","Legendärer Vampirgraf",{book:1,movie:1,horror:1,villain:1,powers:1,royalty:1,nonhuman:1}),
  f("Frankenstein's Monster","⚡","Von Menschen erschaffenes Monster",{book:1,movie:1,horror:1,nonhuman:1}),
  f("Chucky","🔪","Mörderische Puppe",{movie:1,horror:1,villain:1,nonhuman:1}),
  f("Peter Pan","🧚","Junge, der niemals erwachsen wird",{disney:1,book:1,animated:1,movie:1,magic:1,young:1,protagonist:1}),
  f("Captain Hook","🏴‍☠️","Piratischer Erzfeind von Peter Pan",{disney:1,book:1,animated:1,movie:1,villain:1,hat:1}),
  f("Winnie the Pooh","🍯","Honigliebender Bär",{disney:1,book:1,animated:1,animal:1,nonhuman:1}),
  f("Paddington Bear","🍊","Höflicher Bär aus Peru",{book:1,movie:1,animal:1,nonhuman:1,hat:1}),
  f("Pippi Longstocking","🧦","Ungewöhnlich starkes Mädchen mit roten Zöpfen",{female:1,book:1,tv:1,young:1,powers:1,red:1}),
  f("Gandalf","🧙","Weiser Zauberer aus Mittelerde",{book:1,movie:1,magic:1,powers:1,hat:1}),
  f("Frodo Baggins","💍","Hobbit und Ringträger",{book:1,movie:1,protagonist:1,nonhuman:1}),
  f("Gollum","💍","Vom Ring besessener Bewohner Mittelerdes",{book:1,movie:1,villain:1,nonhuman:1}),
  f("Katniss Everdeen","🏹","Heldin der Tribute von Panem",{female:1,book:1,movie:1,young:1,protagonist:1}),
  f("Percy Jackson","🔱","Junger Halbgott und Abenteurer",{book:1,tv:1,movie:1,magic:1,powers:1,young:1,protagonist:1}),
  f("Alice in Wonderland","🐇","Mädchen im Wunderland",{female:1,book:1,disney:1,animated:1,movie:1,young:1,protagonist:1}),
  f("Willy Wonka","🍫","Exzentrischer Schokoladenfabrikant",{book:1,movie:1,hat:1}),
  f("Mr. Bean","🧸","Wortkarger britischer Comedy-Charakter",{tv:1,movie:1,comedian:1,european:1}),
  f("Rick Sanchez","🧪","Genialer dimensionsreisender Wissenschaftler",{animated:1,tv:1,scientist:1,space:1,protagonist:1}),
  f("Morty Smith","😰","Ricks nervöser Enkel",{animated:1,tv:1,space:1,young:1,protagonist:1}),
  f("Stewie Griffin","🧠","Hochintelligentes Baby aus Family Guy",{animated:1,tv:1,young:1,protagonist:1}),
  f("Peppa Pig","🐷","Fröhliches animiertes Schweinchen",{female:1,animated:1,tv:1,animal:1,nonhuman:1,young:1}),
  f("Dora the Explorer","🎒","Junge animierte Entdeckerin",{female:1,animated:1,tv:1,young:1,protagonist:1}),
  f("Bluey","🐶","Junger blauer Cartoon-Hund",{female:1,animated:1,tv:1,animal:1,nonhuman:1,young:1}),
  f("Optimus Prime","🚛","Anführer der Autobots",{robot:1,nonhuman:1,movie:1,animated:1,protagonist:1}),
  f("Bumblebee","🚗","Gelber Autobot und Held",{robot:1,nonhuman:1,movie:1,animated:1,protagonist:1}),
  f("King Kong","🦍","Gigantischer Film-Gorilla",{movie:1,animal:1,nonhuman:1,powers:1}),
  f("Po","🐼","Kung-Fu-Panda und Drachenkrieger",{animated:1,movie:1,animal:1,nonhuman:1,protagonist:1}),
  f("Megamind","🧠","Blauer Superschurke mit Heldenpotenzial",{animated:1,movie:1,villain:1,nonhuman:1,protagonist:1})
);

// Important online personalities that are poorly represented by Wikipedia's
// general pageview lists. These local records keep the public build complete
// without requiring a runtime API or backend.
characters.push(
  p("MontanaBlack","🎮","Deutscher Twitch-Streamer und YouTuber",{creator:1,internet:1,streamer:1,twitchStreamer:1,youtuber:1,gamingStreamer:1,varietyStreamer:1,german:1,european:1}),
  p("Trymacs","🎮","Deutscher Streamer und Webvideoproduzent",{creator:1,internet:1,streamer:1,twitchStreamer:1,youtuber:1,gamingStreamer:1,varietyStreamer:1,german:1,european:1}),
  p("Gronkh","🎮","Deutscher Gaming-YouTuber und Livestreamer",{creator:1,internet:1,streamer:1,twitchStreamer:1,youtuber:1,gamingStreamer:1,german:1,european:1}),
  p("Rezo","🎙️","Deutscher Webvideoproduzent und Musiker",{creator:1,internet:1,youtuber:1,commentaryCreator:1,politicalStreamer:1,musicCreator:1,musician:1,german:1,european:1}),
  p("Knossi","👑","Deutscher Entertainer und Livestreamer",{creator:1,internet:1,streamer:1,twitchStreamer:1,irlStreamer:1,varietyStreamer:1,german:1,european:1}),
  p("EliasN97","⚽","Deutscher Streamer mit Gaming- und Fußballinhalten",{creator:1,internet:1,streamer:1,twitchStreamer:1,gamingStreamer:1,sportsGameStreamer:1,sportsCreator:1,german:1,european:1}),
  p("BastiGHG","⛏️","Deutscher Minecraft-Streamer und YouTuber",{creator:1,internet:1,streamer:1,twitchStreamer:1,youtuber:1,gamingStreamer:1,minecraftStreamer:1,german:1,european:1}),
  p("LetsHugo","🎮","Deutscher Twitch-Streamer",{creator:1,internet:1,streamer:1,twitchStreamer:1,gamingStreamer:1,varietyStreamer:1,german:1,european:1}),
  p("Unge","🎥","Deutscher Webvideoproduzent und Streamer",{creator:1,internet:1,streamer:1,twitchStreamer:1,youtuber:1,gamingStreamer:1,german:1,european:1}),
  p("Paluten","⛏️","Deutscher Gaming-YouTuber",{creator:1,internet:1,youtuber:1,gamer:1,minecraftStreamer:1,gamingStreamer:1,german:1,european:1}),
  p("Dagi Bee","💄","Deutsche Beauty-YouTuberin",{female:1,creator:1,internet:1,youtuber:1,beautyCreator:1,german:1,european:1}),
  p("Julien Bam","🎬","Deutscher Webvideoproduzent, Musiker und Tänzer",{creator:1,internet:1,youtuber:1,comedyCreator:1,musicCreator:1,musician:1,dancer:1,german:1,european:1}),
  p("LaserLuca","🎥","Deutscher YouTuber und Entertainer",{creator:1,internet:1,youtuber:1,comedyCreator:1,varietyStreamer:1,german:1,european:1}),
  p("HandOfBlood","🎮","Deutscher Gaming-YouTuber und Streamer",{creator:1,internet:1,youtuber:1,streamer:1,twitchStreamer:1,gamingStreamer:1,german:1,european:1}),
  p("xQc","🎮","Kanadischer Twitch-Streamer",{creator:1,internet:1,streamer:1,twitchStreamer:1,gamingStreamer:1,varietyStreamer:1,canadian:1}),
  p("Pokimane","🎮","Kanadisch-marokkanische Twitch-Streamerin",{female:1,creator:1,internet:1,streamer:1,twitchStreamer:1,gamingStreamer:1,varietyStreamer:1,canadian:1}),
  p("Ninja","🎮","US-amerikanischer Gaming-Streamer",{creator:1,internet:1,streamer:1,twitchStreamer:1,gamingStreamer:1,battleRoyaleStreamer:1,competitiveGameStreamer:1,american:1}),
  p("Shroud","🎯","Kanadischer Shooter-Streamer",{creator:1,internet:1,streamer:1,twitchStreamer:1,gamingStreamer:1,shooterStreamer:1,competitiveGameStreamer:1,canadian:1}),
  p("Valkyrae","🎮","US-amerikanische YouTube-Streamerin",{female:1,creator:1,internet:1,streamer:1,youtubeStreamer:1,youtuber:1,gamingStreamer:1,varietyStreamer:1,american:1}),
  p("Ludwig Ahgren","🎙️","US-amerikanischer Streamer und Podcaster",{creator:1,internet:1,streamer:1,youtubeStreamer:1,varietyStreamer:1,podcaster:1,american:1}),
  p("Sykkuno","🎮","US-amerikanischer Gaming-Streamer",{creator:1,internet:1,streamer:1,twitchStreamer:1,gamingStreamer:1,varietyStreamer:1,american:1}),
  p("Mizkif","🎥","US-amerikanischer Twitch-Streamer",{creator:1,internet:1,streamer:1,twitchStreamer:1,irlStreamer:1,varietyStreamer:1,american:1}),
  p("Asmongold","⚔️","US-amerikanischer Gaming-Streamer",{creator:1,internet:1,streamer:1,twitchStreamer:1,gamingStreamer:1,varietyStreamer:1,american:1}),
  p("MoistCr1TiKaL","🎙️","US-amerikanischer YouTuber und Streamer",{creator:1,internet:1,streamer:1,youtuber:1,twitchStreamer:1,commentaryCreator:1,gamingStreamer:1,american:1}),
  p("Markiplier","🎮","US-amerikanischer Gaming-YouTuber",{creator:1,internet:1,youtuber:1,gamer:1,gamingStreamer:1,american:1}),
  p("Jacksepticeye","🎮","Irischer Gaming-YouTuber",{creator:1,internet:1,youtuber:1,gamer:1,gamingStreamer:1,irish:1,european:1}),
  p("Bonnie Blue","📱","Britische Darstellerin in Erwachsenenfilmen und Online-Creatorin",{female:1,actor:1,creator:1,internet:1,adultCreator:1,adultFilmPerformer:1,onlyFansCreator:1,british:1,european:1}),
  p("Abella Danger","🎬","US-amerikanische Darstellerin in Erwachsenenfilmen",{female:1,actor:1,adultCreator:1,adultFilmPerformer:1,american:1}),
  p("Angela White","🎬","Australische Darstellerin und Regisseurin in Erwachsenenfilmen",{female:1,actor:1,director:1,adultCreator:1,adultFilmPerformer:1,adultDirector:1,australian:1}),
  p("Eva Elfie","🎬","Russische Darstellerin in Erwachsenenfilmen",{female:1,actor:1,adultCreator:1,adultFilmPerformer:1,russian:1,european:1}),
  p("Sasha Grey","🎬","US-amerikanische Schauspielerin und ehemalige Adult-Darstellerin",{female:1,actor:1,adultCreator:1,adultFilmPerformer:1,retired:1,american:1}),
  p("Belle Delphine","📱","Britische Internetpersönlichkeit und Adult-Creatorin",{female:1,creator:1,internet:1,adultCreator:1,onlyFansCreator:1,british:1,european:1}),
  p("Corinna Kopf","📱","US-amerikanische Internetpersönlichkeit und Streamerin",{female:1,creator:1,internet:1,streamer:1,onlyFansCreator:1,adultCreator:1,irlStreamer:1,american:1})
);
