import {readFile,writeFile} from 'node:fs/promises';
import {characters,questions} from '../data.js';
import {GuessEngine} from '../engine.js';
import {rankingFeatures,questionKind,answerability,rankingKinds} from '../question-ranking.js';
const engine=new GuessEngine(structuredClone(characters),questions);
engine.addDatabase(JSON.parse(await readFile('wikidata-people.json','utf8')));
engine.refreshGeneratedQuestions();
// Explicit bootstrap assumptions about user knowledge. Never present these as
// observed player labels. A future consented dataset can replace this teacher.
export const assumptions={basic:.92,group:.82,evidence:.82,genre:.78,party:.75,team:.79,member:.66,award:.48,work:.84,universe:.92,appearance:.88,instrument:.8,office:.86,position:.7,field:.67,label:.3,conflict:.55,birthplace:.25,education:.22,employer:.38};
Object.assign(assumptions,{occupation:.85,language:.65,nativeLanguage:.65,movement:.4,creator:.52,inspiration:.35,father:.45,mother:.45,spouse:.6,child:.48,sibling:.48,partner:.55,burial:.2,deathCause:.35,castWork:.84,voiceWork:.8,authorWork:.84,performerWork:.82,composerWork:.73,directorWork:.82,firstAppearance:.55,comicDebut:.35,entityType:.8,event:.65,participation:.7,militaryBranch:.6,militaryRank:.55});
Object.assign(assumptions,{militaryUnit:.55,constituency:.48,creditedWork:.8,weightClass:.8});
Object.assign(assumptions,{transformation:.92,adBrand:.84});
for(const kind of rankingKinds) if(!Number.isFinite(assumptions[kind]))throw Error(`Missing answerability assumption: ${kind}`);
let seed=731; const random=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/2**32);
const all=[...engine.questions,...engine.generatedQuestions];
const samples=[];
for(let index=0;index<12000;index++) {
  const q=all[Math.floor(random()*all.length)],stage=Math.floor(random()*30);
  const length=(q.en||q.de).length;
  const p=Math.max(.12,assumptions[questionKind(q)]-.001*Math.max(0,length-90));
  samples.push({x:rankingFeatures(q,stage),y:Number(random()<p),id:q.id});
}
// Stable feature-ID holdout: paraphrases of a question cannot leak across sets.
const hash=id=>[...id].reduce((value,c)=>(Math.imul(value,31)+c.charCodeAt(0))>>>0,0);
const training=samples.filter(row=>hash(row.id)%5!==0),validation=samples.filter(row=>hash(row.id)%5===0);
const weights=Array(rankingFeatures(all[0]).length).fill(0); weights[0]=.6;
for(let epoch=0;epoch<25;epoch++) for(const row of training) {
  const prediction=row.x.reduce((sum,value,index)=>sum+value*weights[index],0);
  const error=Math.max(-1,Math.min(1,prediction-row.y));
  for(let i=0;i<weights.length;i++) weights[i]-=.006*(error*row.x[i]+.0001*weights[i]);
}
const model={version:1,trained:new Date().toISOString().slice(0,10),source:'synthetic answerability bootstrap; not real player data',features:['bias',...rankingKinds,'length','stage'],weights:weights.map(value=>Number(value.toFixed(6))),training:training.length,holdout:validation.length,assumptions};
const loss=(rows,predict)=>rows.reduce((sum,row)=>sum+(predict(row)-row.y)**2,0)/rows.length;
const mean=training.reduce((sum,row)=>sum+row.y,0)/training.length;
model.validation={brier:loss(validation,row=>Math.max(.12,Math.min(.98,row.x.reduce((sum,v,i)=>sum+v*model.weights[i],0)))),constantBrier:loss(validation,()=>mean)};
if(model.validation.brier>=model.validation.constantBrier) throw Error('Ranker failed held-out answerability gate');
await writeFile('ranking-model.js',`// Generated by npm run train:ranker. See source/assumptions, not user-trained.\nexport const rankingModel = ${JSON.stringify(model,null,2)};\n`);
console.log(JSON.stringify(model.validation),`trained ${training.length}, held out ${validation.length}`);
